answers:
  - "Sei nicht albern."
  - "Ich habe nicht das richtige Werkzeug."
  - "Ich weis nicht wie das geht."
  - "lässt mich nicht."
  - "Zu schwer."
  - "Kann ich nicht erreichen."
  - "Ich habe zuviel zu tragen.\nIch müsste etwas weglegen."
  - "Gut."